apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/quick-start/minimal
- ingress.yaml

namespace: argo

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: argo-server
  spec:
    template:
      spec:
        containers:
        - name: argo-server
          env:
          - name: BASE_HREF
            value: /argo/