apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argocd-managed/argo-workflows/base
    repoURL: https://github.com/lordpangan/dev-k8s.git
    targetRevision: HEAD